import { ArrowRight, Sparkles } from "lucide-react";

const tags = ["Office", "Summer", "Minimal"];
const items = ["White Shirt", "Navy Chinos", "White Sneakers", "Silver Watch"];

export default function TodaysOutfit() {
  return (
    <section className="relative overflow-hidden rounded-[32px] border border-white/10 bg-[linear-gradient(135deg,rgba(255,255,255,0.12),rgba(255,255,255,0.06))] p-6 shadow-[0_30px_90px_rgba(0,0,0,0.28)] backdrop-blur-2xl sm:p-7">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(168,85,247,0.2),_transparent_45%)]" />
      <div className="relative z-10">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.3em] text-purple-300/80">
              Today&apos;s Outfit
            </p>
            <h3 className="mt-2 text-2xl font-semibold text-white">
              Modern Smart Casual
            </h3>
            <p className="mt-2 max-w-xl text-sm leading-6 text-zinc-400">
              Generated by AI based on today&apos;s weather and your style profile.
            </p>
          </div>
          <div className="rounded-full border border-purple-400/20 bg-purple-500/10 px-3 py-1.5 text-sm font-semibold text-purple-200">
            98%
          </div>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
          <div className="relative min-h-[260px] overflow-hidden rounded-[28px] border border-white/10 bg-[radial-gradient(circle_at_top,_rgba(168,85,247,0.25),_transparent_40%),linear-gradient(145deg,_rgba(255,255,255,0.12),_rgba(255,255,255,0.04))] p-6">
            <div className="absolute inset-0 bg-[linear-gradient(120deg,transparent_0%,rgba(255,255,255,0.06)_50%,transparent_100%)]" />
            <div className="relative flex h-full flex-col justify-between">
              <div className="flex items-center justify-between">
                <span className="rounded-full border border-white/10 bg-black/20 px-3 py-1 text-xs uppercase tracking-[0.3em] text-zinc-300">
                  Style Pick
                </span>
                <div className="flex items-center gap-2 rounded-full border border-purple-400/20 bg-purple-500/10 px-3 py-1 text-sm text-purple-200">
                  <Sparkles className="h-4 w-4" />
                  Premium
                </div>
              </div>

              <div className="space-y-3">
                <div className="h-16 w-24 rounded-[20px] border border-white/10 bg-white/10" />
                <div className="h-20 w-32 rounded-[24px] border border-white/10 bg-white/10" />
                <div className="h-12 w-20 rounded-[16px] border border-white/10 bg-white/10" />
              </div>
            </div>
          </div>

          <div>
            <div className="flex flex-wrap gap-2">
              {tags.map((tag) => (
                <span
                  key={tag}
                  className="rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-sm text-zinc-200"
                >
                  {tag}
                </span>
              ))}
            </div>

            <div className="mt-5 rounded-[24px] border border-white/10 bg-black/20 p-4 shadow-inner shadow-black/20">
              <div className="flex items-center justify-between text-sm text-zinc-300">
                <span>Recommendation Score</span>
                <span className="font-semibold text-white">98%</span>
              </div>
              <div className="mt-3 space-y-2">
                {items.map((item) => (
                  <div key={item} className="text-sm text-zinc-300">
                    • {item}
                  </div>
                ))}
              </div>
            </div>

            <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-[24px] border border-white/10 bg-white/10 p-4">
              <div>
                <p className="text-sm text-zinc-400">Estimated Cost</p>
                <p className="text-lg font-semibold text-white">₹4,850</p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button className="rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm font-medium text-white transition-all duration-300 hover:-translate-y-0.5 hover:bg-white/15">
                  View Details
                </button>
                <button className="rounded-full bg-gradient-to-r from-purple-500 via-fuchsia-500 to-violet-500 px-4 py-2 text-sm font-semibold text-white shadow-[0_0_30px_rgba(168,85,247,0.3)] transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_0_40px_rgba(168,85,247,0.4)]">
                  Change Style
                  <ArrowRight className="ml-2 inline h-4 w-4" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
